service: mr-ed
runtime: python39
entrypoint: gunicorn -b :$PORT EDMapService.wsgi

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  DJANGO_SETTINGS_MODULE: "MrED.settings"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto