# Generated by Django 4.2.6 on 2023-12-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDUserManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
